name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  segmented_button_slide: ^2.0.0
  flutter_svg: ^2.0.17
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  toastification: ^3.0.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  dio_cookie_manager: ^3.2.0
  dio: ^5.8.0+1
  cookie_jar: ^4.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/notification.png
    - assets/images/bell.png
    - assets/images/history.png
    - assets/icons/search.svg
    - assets/icons/eye.svg
    - assets/icons/eye_slash.svg
    - assets/icons/bell-regular.svg
    - assets/images/profile.png
    - .env

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/workSans/WorkSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
